### ISSUE TITLE
Question on LSTM average pooling

### ISSUE THREAD

**Issue by debanjanghosh** [yanghanxy/CIAN#1]
Nice work! I was wondering where did you implement the average pooling on top of the LSTM (as described in your paper)? Best!

**Comment by yanghanxy** [comment]
Hi @debanjanghosh , 
You can take a look on this tutorial with detailed explanation regarding LSTM with average pooling: [http://deeplearning.net/tutorial/lstm.html#our-model](http://deeplearning.net/tutorial/lstm.html#our-model)
I didn't implement it in this repository, but you can implement it easily with Keras. 
Best, Han
